# -*- coding: utf-8 -*-
"""ex.V0.10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mi2zMZCVVW5ItZjZTcYSVySUM_9vtDfB
"""

# making a tuple (A Tuple is same like list, but the value of tuple can't changed or modified)
dimensions_tuple = (1900, 2024)

print(dimensions_tuple)