# -*- coding: utf-8 -*-
"""ex.V0.8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mi2zMZCVVW5ItZjZTcYSVySUM_9vtDfB
"""

# Copying a List
square = [x**2 for x in range(1, 1000)]

copied_list = square[:]

print(copied_list)