# -*- coding: utf-8 -*-
"""ex.V0.3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mi2zMZCVVW5ItZjZTcYSVySUM_9vtDfB
"""

# Getting Last item from list
countries_list = ["Pakistan", "India", "Albania", "Afghanistan", "USA","Bangladesh","Bosnia and Herzegovina" ]
print(countries_list[-1])