# -*- coding: utf-8 -*-
"""ex.V0.7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mi2zMZCVVW5ItZjZTcYSVySUM_9vtDfB
"""

# Selecting first 2 elements
square = [x**2 for x in range(10, 1000)]

print(square[:2])