# -*- coding: utf-8 -*-
"""ex.V0.5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mi2zMZCVVW5ItZjZTcYSVySUM_9vtDfB
"""

# Making Numerical Lists
squre = []

for x in range(1, 11):
    squre.append(x**4)

print(squre)