# -*- coding: utf-8 -*-
"""ex.V0.9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mi2zMZCVVW5ItZjZTcYSVySUM_9vtDfB
"""

a = [20, "as it is", "abc", 10+10j]

a[3] = 9+1j
a.append('chaha patho')

print(a)