# -*- coding: utf-8 -*-
"""ex.V0.4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mi2zMZCVVW5ItZjZTcYSVySUM_9vtDfB
"""

# Prints all values one-by-one
countries_list = ["Pakistan", "India", "Japan", "China", "USA"]

for x in countries_list:
    print(x)