# -*- coding: utf-8 -*-
"""ex.V0.6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mi2zMZCVVW5ItZjZTcYSVySUM_9vtDfB
"""

# List Comprehension

square = [x**2 for x in range(1, 11)]

print(square)