# -*- coding: utf-8 -*-
"""logistic regression project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VVsKv6YaBFmr2lp75J3UehEiyD75KHwk
"""

# Import necessary libraries
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Load the Iris dataset
data = load_iris()
X, y = data.data, data.target

# We'll perform binary classification (Setosa vs. Not Setosa)
# So, we'll modify the target labels to create a binary classification problem
y_binary = (y == 0).astype(int)  # 1 for Setosa, 0 for Not Setosa

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y_binary, test_size=0.3, random_state=42)

# Create a logistic regression model
logistic_reg = LogisticRegression()

# Fit the model on the training data
logistic_reg.fit(X_train, y_train)

# Make predictions on the test data
y_pred = logistic_reg.predict(X_test)

# Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred, target_names=['Not Setosa', 'Setosa'])

# Print the accuracy and classification report
print(f"Accuracy: {accuracy:.2f}")
print("Classification Report:\n", report)